// #45 — Resolve a framework's control mapping against live tenant data, and render an exportable
// HTML report. Evidence values are real counts pulled from the store at generation time.
import { FRAMEWORKS } from "../data/compliance.js";
import { oidcConfig, samlConfig } from "./sso.js";

export const FRAMEWORK_LIST = Object.entries(FRAMEWORKS).map(([key, f]) => ({ key, name: f.name }));

export function buildReport(store, tenant, fwKey, counts) {
  const fw = FRAMEWORKS[fwKey];
  if (!fw) return null;
  const stats = store.stats(tenant);
  const inv = store.inventory(tenant);
  const posture = inv.length ? Math.round(inv.reduce((s, d) => s + (d.posture ?? 100), 0) / inv.length) : null;
  const oidc = oidcConfig(store), saml = samlConfig(store);
  const ssoStatus = (oidc.enabled || saml.enabled)
    ? "SSO " + [oidc.enabled && "OIDC", saml.enabled && "SAML"].filter(Boolean).join("+")
    : "password";
  const M = {
    promptsReviewed: { label: "Prompts reviewed", value: stats.prompts.total },
    promptsBlocked: { label: "Prompts blocked", value: stats.prompts.blocked },
    alerts: { label: "Policy alerts logged", value: stats.total },
    auditEvents: { label: "Audited events", value: stats.total },
    devices: { label: "Devices monitored", value: inv.length },
    threatDetectors: { label: "Threat detectors", value: counts.threats },
    contentCategories: { label: "Content categories", value: counts.content },
    postureAvg: { label: "Avg device posture", value: posture == null ? "—" : posture + "/100" },
    encryption: { label: "Secrets encryption", value: "AES-256-GCM at rest" },
    sso: { label: "Admin authentication", value: ssoStatus },
    tenantIsolation: { label: "Tenant isolation", value: "enforced server-side" }
  };
  const controls = fw.controls.map((c) => ({ id: c.id, name: c.name, raiseme: c.raiseme, status: c.status, evidence: (c.metrics || []).map((k) => M[k]).filter(Boolean) }));
  return { framework: fw.name, frameworkKey: fwKey, tenant, generatedAt: new Date().toISOString(), summary: { total: controls.length, implemented: controls.filter((c) => c.status === "implemented").length }, controls };
}

export function renderReportHtml(rep) {
  const esc = (s) => String(s).replace(/[&<>]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" }[c]));
  const rows = rep.controls.map((c) => `<tr>
    <td class="id">${esc(c.id)}</td>
    <td><b>${esc(c.name)}</b><div class="rm">${esc(c.raiseme)}</div></td>
    <td>${c.evidence.map((e) => `<div><span class="el">${esc(e.label)}:</span> ${esc(e.value)}</div>`).join("") || "—"}</td>
    <td><span class="st">&#10003; ${esc(c.status)}</span></td>
  </tr>`).join("");
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>RAISEME — ${esc(rep.framework)} — ${esc(rep.tenant)}</title>
  <style>body{font-family:Inter,system-ui,Arial,sans-serif;color:#1a1f2b;max-width:1000px;margin:32px auto;padding:0 20px}
  h1{font-size:22px;margin:0}.sub{color:#667;font-size:13px;margin:4px 0 20px}
  .sum{background:#f4f7fb;border:1px solid #dde4ee;border-radius:10px;padding:14px 18px;margin-bottom:20px;font-size:14px}
  table{border-collapse:collapse;width:100%;font-size:13px}th,td{border:1px solid #e2e8f2;padding:9px 11px;text-align:left;vertical-align:top}
  th{background:#0e1116;color:#e6edf3;font-weight:600}.id{font-family:ui-monospace,monospace;white-space:nowrap;color:#2f6fe0}
  .rm{color:#556;margin-top:4px;font-size:12px}.el{color:#889;font-size:12px}.st{color:#1a7f37;font-weight:700;white-space:nowrap}
  .ft{color:#889;font-size:11px;margin-top:18px}</style></head><body>
  <h1>RAISEME — Compliance mapping</h1>
  <div class="sub">${esc(rep.framework)} &middot; tenant <b>${esc(rep.tenant)}</b> &middot; generated ${esc(rep.generatedAt)}</div>
  <div class="sum"><b>${rep.summary.implemented}/${rep.summary.total}</b> controls addressed by RAISEME. Evidence values are live counts for this tenant.</div>
  <table><thead><tr><th>Control</th><th>RAISEME mapping</th><th>Evidence (live)</th><th>Status</th></tr></thead><tbody>${rows}</tbody></table>
  <div class="ft">Generated by RAISEME. This maps RAISEME's controls to the framework for self-assessment; it is not a certification or independent audit attestation.</div>
  </body></html>`;
}
